config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users

  resources :profiles, only: [:index, :show, :create, :new]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index, :show, :create, :new]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord

  COVERAGES = [
    5000,
    10000,
    15000,
    20000,
  ]

  validates_presence_of :name, :birthday, :address, :email, :salary, :coverage

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/profiles_controller.rb
class Api::V1::ProfilesController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def index
    profiles = Profile.all
    render json: profiles
  end

  def show
    profile = Profile.find(params[:id])
    render json: profile
  end

  def create
    profile = Profile.new(profile_params)
    if profile.save
      render json: profile, status: :created
    else
      render json: {error: profile.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :birthday, :address, :email, :salary, :coverage, :id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:email)
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
  end

  def show
  end

end

app/views/homes/index.html.erb
<div class="landing-page">
  <br />
  <h3 class="welcome">Welcome to a world where insurance is made easy by Coterie!</h3>
  <br />
  <ul>
    <%- if current_user -%>
      <li class="start button large orange"><%= link_to 'START HERE', profiles_path %></li>
    <%- else -%>
      <li class="start button large orange"><%= link_to 'SIGN UP', new_user_registration_path %></li>
      <li class="start button large orange"><%= link_to 'SIGN IN', new_user_session_path %></li>
    <%- end -%>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>COTERIE</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <h3 class="coterie"><a href="/">COTERIE</a></h3>

    <section class="top-bar-section">
      <div class="right">
        <%- if current_user -%>
          <p class="header-links"><%= link_to 'SIGN OUT', destroy_user_session_path, method: :delete %></p>
        <%- else -%>
          <p class="header-links"><%= link_to 'SIGN UP', new_user_registration_path %></p>
          <p class="header-links"><%= link_to 'SIGN IN', new_user_session_path %></p>
        <%- end -%>
      </div>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/profiles/index.html.erb
<div id="app">
</div>

app/views/profiles/new.html.erb
<div id="app">
</div>

app/views/profiles/show.html.erb
<div id="app">
</div>